// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import config from "@/configs/activeConfig";

// استخدم متغيرات البيئة من Vite
const SUPABASE_URL = config.supabaseUrl;
const SUPABASE_ANON_KEY = config.supabaseKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    // أضف هذا الجزء لتثبيت الهارت بيت وإعادة الاتصال
    realtime: {
      // كل 30 ثانية نبضة حياة
      heartbeatIntervalMs: 30000,
      // عشان ما يطلب أكثر من اللازم
      reconnectAfterMs: (retryCount: number) =>
        Math.min(1000 * 2 ** retryCount, 30000)
    }
  }
);
// إذا لم تضفها بعد، ثم أعد تشغيل dev server:
if (import.meta.env.DEV) {
  // @ts-expect-error: Expose supabase client on window for debugging in DEV mode
  window.supabase = supabase;
}
